"""Extraction of the SQL query from raw model output.

The model is instructed (see `prompt_formatter.SYSTEM_PROMPT`) to respond
with only a ```sql fenced code block. Anything else it emits (explanation
text, missing fence, wrong language tag) is a format failure, not a script
error — `extract_sql` returns `None` in that case, and callers must treat
that `None` as an honest "model did not follow the output format"
result (see technical_assignment.md metrics: parse-failure rate is
reported separately from execution accuracy).
"""

from __future__ import annotations

import re

# Non-greedy match so multiple fenced blocks in one response yield only
# the first one; DOTALL so the SQL body can span multiple lines.
SQL_FENCE_PATTERN = re.compile(r"```sql\s*(.*?)\s*```", re.DOTALL)


def extract_sql(raw_model_output: str) -> str | None:
    """Extract the SQL query from a ```sql-fenced model response.

    Args:
        raw_model_output: The raw text generated by the model.

    Returns:
        The SQL query with surrounding whitespace stripped, or `None` if
        no ```sql fenced block is present.
    """
    match = SQL_FENCE_PATTERN.search(raw_model_output)
    if match is None:
        return None
    return match.group(1).strip()
